@startuml
title Добавление в черный список
alt Стандартное добавление в черный список
    Пользователь->Приложение: Нажатие на кнопку <...>
    activate Приложение
    Приложение->Пользователь: Список возможных действий
    deactivate Приложение
    Пользователь->Приложение: Нажатие на кнопку "Добавить пользователя в черный список"
    activate Приложение
    Приложение->Пользователь: Окно подтверждения
    deactivate Приложение

    alt Подтверждение добавления
        Пользователь->Приложение: Нажатие на кнопку <Да, добавить в черный список>
        Приложение->Сервер: Запрос на изменения данных
        alt Успешное добавление
            Сервер->Приложение: Код успешного добавления
            Приложение->Пользователь: Сообщение об успешном добавлении в черный список
        else Ошибка добавления
            Сервер->Приложение: Код ошибки добавления
            Приложение->Пользователь: Сообщение об ошибке добавления
        end
    else Отклонение добавления
         Пользователь->Приложение: Нажатие на кнопку <Отмена>
         activate Приложение
         Приложение->Пользователь: Отображение страницу Пользователя Б
         deactivate Приложение
    end
@enduml