@startuml
title Блокировка звонков

alt Стандартная блокировка звонков

    Пользователь->Приложение: Нажатие на кнопку <...>
    activate Приложение
    Приложение->Пользователь: Список возможных действий
    deactivate Приложение
    Пользователь->Приложение: Нажатие на кнопку "Блокировать звонки"
    activate Приложение
    Приложение->Пользователь: Окно подтверждения
    deactivate Приложение

    alt Подтверждение блокировки
        Пользователь->Приложение: Нажатие на кнопку <Да, блокировать звонки>

        Приложение->Сервер: Запрос на изменения данных

        alt Успешная блокировка

            Сервер->Приложение: Код успешной блокировки
            Приложение->Пользователь: Сообщение об успешной блокировке звонков

        else Ошибка блокировки

            Сервер->Приложение: Код ошибки блокировки
            Приложение->Пользователь: Сообщение об ошибке блокировки звонков

        end
    else Отклонение блокировки
        Пользователь->Приложение: Нажатие на кнопку <Отмена>
        activate Приложение
        Приложение->Пользователь: Отображение страницу Пользователя Б
        deactivate Приложение
    end
@enduml